package com.faifai.rider;
import android.app.*;import android.content.*;import android.media.*;import android.net.Uri;import androidx.core.app.NotificationCompat;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.*;
public class RiderOrderService extends Service{
 public static final String ACTION_START="com.faifai.rider.START",ACTION_ACCEPT="com.faifai.rider.ACCEPT",ACTION_REJECT="com.faifai.rider.REJECT";private static final String BASE="https://vita-napoli-backend-usman.onrender.com/api/v1/rider";private final ScheduledExecutorService w=Executors.newSingleThreadScheduledExecutor();private MediaPlayer alarm;
 @Override public void onCreate(){super.onCreate();NotificationManager n=getSystemService(NotificationManager.class);n.createNotificationChannel(new NotificationChannel("rider_active","Rider service",NotificationManager.IMPORTANCE_LOW));NotificationChannel c=new NotificationChannel("rider_orders","New delivery orders",NotificationManager.IMPORTANCE_HIGH);c.setSound(null,null);c.enableVibration(true);n.createNotificationChannel(c);startForeground(61,new NotificationCompat.Builder(this,"rider_active").setSmallIcon(android.R.drawable.ic_menu_directions).setContentTitle("Fai Fai Rider active").setContentText("Checking delivery orders in background").setOngoing(true).setContentIntent(open()).build());w.scheduleWithFixedDelay(this::poll,0,10,TimeUnit.SECONDS);}
 @Override public int onStartCommand(Intent i,int f,int id){if(i!=null&&(ACTION_ACCEPT.equals(i.getAction())||ACTION_REJECT.equals(i.getAction()))){int a=i.getIntExtra("assignment_id",0);String s=ACTION_ACCEPT.equals(i.getAction())?"accepted":"rejected";w.execute(()->update(a,s));}return START_STICKY;}
 private void poll(){int rider=getSharedPreferences("fai_fai_rider",MODE_PRIVATE).getInt("rider_id",0);if(rider<=0){stopAlarm();return;}try{JSONArray a=new JSONObject(req("GET",BASE+"/deliveries/"+rider,null)).optJSONArray("items");JSONObject found=null;if(a!=null)for(int x=0;x<a.length();x++){JSONObject o=a.getJSONObject(x);if("assigned".equalsIgnoreCase(o.optString("status"))){found=o;break;}}if(found==null)stopAlarm();else notifyOrder(found);}catch(Exception ignored){}}
 private synchronized void notifyOrder(JSONObject o){int id=o.optInt("id"),order=o.optInt("order_id");Notification n=new NotificationCompat.Builder(this,"rider_orders").setSmallIcon(android.R.drawable.ic_dialog_alert).setContentTitle("New Delivery #"+order).setContentText("Accept or reject this delivery").setCategory(NotificationCompat.CATEGORY_ALARM).setPriority(NotificationCompat.PRIORITY_MAX).setOngoing(true).setContentIntent(open()).addAction(0,"ACCEPT",action(ACTION_ACCEPT,id,1)).addAction(0,"REJECT",action(ACTION_REJECT,id,2)).build();getSystemService(NotificationManager.class).notify(62,n);android.content.SharedPreferences p=getSharedPreferences("fai_fai_rider",MODE_PRIVATE);if(p.getBoolean("native_sound",true)&&alarm==null)try{String saved=p.getString("ringtone_uri","");Uri u=(saved==null||saved.isEmpty())?android.media.RingtoneManager.getDefaultUri(android.media.RingtoneManager.TYPE_ALARM):Uri.parse(saved);alarm=new MediaPlayer();alarm.setDataSource(this,u);alarm.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).build());alarm.setLooping(true);alarm.prepare();alarm.start();}catch(Exception e){stopAlarm();}}
 private PendingIntent action(String a,int id,int code){return PendingIntent.getService(this,code,new Intent(this,RiderOrderService.class).setAction(a).putExtra("assignment_id",id),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}private PendingIntent open(){return PendingIntent.getActivity(this,3,new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 private void update(int id,String s){try{req("PUT",BASE+"/deliveries/"+id+"/status","{\"status\":\""+s+"\"}");}catch(Exception ignored){}stopAlarm();}
 private String req(String method,String url,String body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(12000);c.setRequestMethod(method);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}InputStream in=c.getResponseCode()<400?c.getInputStream():c.getErrorStream();ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[2048];int n;while((n=in.read(b))>=0)out.write(b,0,n);c.disconnect();return out.toString("UTF-8");}
 private synchronized void stopAlarm(){getSystemService(NotificationManager.class).cancel(62);if(alarm!=null){try{alarm.stop();}catch(Exception ignored){}alarm.release();alarm=null;}}@Override public void onDestroy(){w.shutdownNow();stopAlarm();super.onDestroy();}@Override public android.os.IBinder onBind(Intent i){return null;}
}
